# Generated by Django 3.1.3 on 2020-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
        migrations.AddField(
            model_name='status',
            name='duration',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='offline',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='online',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
